/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reportes;


import Conexion.Conexion;
import Joption.Joption;
import Joption.Joptionx;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author JaviieR
 */
public class Equipo extends javax.swing.JFrame {
       DefaultTableModel model;
    Connection conn;
    Statement sent;
    Joption icon = new Joption();
    Joptionx save = new Joptionx(); 
       

    /**
     * Creates new form Equipo
     */
    public Equipo() {
        initComponents();
        todos();
        acti.setVisible(false);
        des.setVisible(false);
        setTitle("Reportes de Equipos");
        setResizable(false);
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("search_16.png")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("wall.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());
    }
    
    
void cargar(String status){           
 String [] titulos ={"Equipo","Marca","Modelo","Serie","Inmovilizado","Ubicacion","Observacion","Status","Sala","Pertenece","Compañia","Registro"};
 String sql = "SELECT * FROM articulos WHERE acti='"+status+"'";
 

 model= new DefaultTableModel(null,titulos);
 Conexion cc= new Conexion();
 Connection cn = cc.getConnection();
        try {
          
          Statement   st = cn.createStatement();
          ResultSet rs=st.executeQuery(sql);
          String [] fila = new String[14];
  while(rs.next()){
           
            fila[0] = rs.getString("equip");
            fila[1] = rs.getString("marc");
            fila[2] = rs.getString("model"); 
            fila[3] = rs.getString("seri"); 
            fila[4] = rs.getString("inmo");
            fila[5] = rs.getString("ubi");
            fila[6] = rs.getString("obser");
            fila[7] = rs.getString("acti"); 
            fila[8] = rs.getString("nom_sala");
            fila[9] = rs.getString("pertenece");
            fila[10] = rs.getString("nom_pertenece");
            fila[11] = rs.getString("fecha");
            
       
           
      model.addRow(fila);
       
  }
        t_evento2.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(Equipo.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
void todos(){           
 String [] titulos ={"Equipo","Marca","Modelo","Serie","Inmovilizado","Ubicacion","Observacion","Status","Sala","Pertenece","Compañia","Registro"};
 String sql = "SELECT * FROM articulos";
 

 model= new DefaultTableModel(null,titulos);
 Conexion cc= new Conexion();
 Connection cn = cc.getConnection();
        try {
          
          Statement   st = cn.createStatement();
          ResultSet rs=st.executeQuery(sql);
          String [] fila = new String[14];
  while(rs.next()){
           
            fila[0] = rs.getString("equip");
            fila[1] = rs.getString("marc");
            fila[2] = rs.getString("model"); 
            fila[3] = rs.getString("seri"); 
            fila[4] = rs.getString("inmo");
            fila[5] = rs.getString("ubi");
            fila[6] = rs.getString("obser");
            fila[7] = rs.getString("acti"); 
            fila[8] = rs.getString("nom_sala");
            fila[9] = rs.getString("pertenece");
            fila[10] = rs.getString("nom_pertenece");
            fila[11] = rs.getString("fecha");
            
       
           
      model.addRow(fila);
       
  }
        t_evento2.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(Equipo.class.getName()).log(Level.SEVERE, null, ex);
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t_evento2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        combostatus = new javax.swing.JComboBox();
        acti = new javax.swing.JButton();
        des = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        t_evento2.setBackground(new java.awt.Color(0, 0, 0));
        t_evento2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_evento2.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        t_evento2.setForeground(new java.awt.Color(255, 255, 255));
        t_evento2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t_evento2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t_evento2.setSelectionBackground(new java.awt.Color(51, 51, 51));
        t_evento2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_evento2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_evento2);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes/search_16.png"))); // NOI18N
        jButton1.setText("OK");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        combostatus.setBackground(new java.awt.Color(0, 102, 255));
        combostatus.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        combostatus.setForeground(new java.awt.Color(255, 255, 255));
        combostatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "ACTIVO", "DESHABILITADO" }));
        combostatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combostatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combostatusActionPerformed(evt);
            }
        });

        acti.setBackground(new java.awt.Color(0, 0, 0));
        acti.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        acti.setForeground(new java.awt.Color(255, 255, 255));
        acti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes/pdf.png"))); // NOI18N
        acti.setText("GENERAR REPORTE");
        acti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actiActionPerformed(evt);
            }
        });

        des.setBackground(new java.awt.Color(0, 0, 0));
        des.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        des.setForeground(new java.awt.Color(255, 255, 255));
        des.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes/pdf.png"))); // NOI18N
        des.setText("GENERAR REPORTE");
        des.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seleccione STATUS :");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes/salir.png"))); // NOI18N
        jButton2.setText("SALIR");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addComponent(combostatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(des)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acti)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combostatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acti, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_evento2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_evento2MouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_t_evento2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        if(combostatus.getSelectedItem().toString().equals("")){
             JOptionPane.showMessageDialog(null,"Seleccione Status","ERROR",JOptionPane.ERROR_MESSAGE,save);
             return;   }
       cargar(combostatus.getSelectedItem().toString());
       
            int fila=t_evento2.getRowCount();
            if(fila<=0){
             JOptionPane.showMessageDialog(null,"Fallo la Busqueda No Se Encontro!","ERROR",JOptionPane.ERROR_MESSAGE,save); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combostatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combostatusActionPerformed
        // TODO add your handling code here:
        int bloqueo = combostatus.getSelectedIndex();
        if(bloqueo == 1){
            acti.setVisible(true);
            des.setVisible(false);
        }
        if(bloqueo == 2){
            des.setVisible(true);
            acti.setVisible(false);
        }
        if(bloqueo == 0){
            acti.setVisible(false);
            des.setVisible(false);
        }
        
        
    }//GEN-LAST:event_combostatusActionPerformed

    private void actiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actiActionPerformed
        // TODO add your handling code here:
  Conexion cc= new Conexion();
 Connection cn = cc.getConnection();
        JasperReport reporte = null;
        String archivo  = "C:\\Program Files\\SCIEC\\ReporteEquipos.jasper";
           try {
               Map parametro = new HashMap();
               parametro.put("genero", combostatus.getSelectedItem());
               reporte = (JasperReport) JRLoader.loadObjectFromFile(archivo);
               JasperPrint jp = JasperFillManager.fillReport(reporte,parametro,cn);
               JasperViewer jv = new JasperViewer(jp);
               jv.setVisible(true);
               setTitle("Reporte");
           } catch (JRException ex) {
               Logger.getLogger(Equipo.class.getName()).log(Level.SEVERE, null, ex);
           }     
    }//GEN-LAST:event_actiActionPerformed

    private void desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desActionPerformed
        // TODO add your handling code here:
          Conexion cc= new Conexion();
 Connection cn = cc.getConnection();
        JasperReport reporte = null;
        String archivo  = "C:\\Program Files\\SCIEC\\ReporteEquipos2.jasper";
           try {
               Map parametro = new HashMap();
               parametro.put("genero", combostatus.getSelectedItem());
               reporte = (JasperReport) JRLoader.loadObjectFromFile(archivo);
               JasperPrint jp = JasperFillManager.fillReport(reporte,parametro,cn);
               JasperViewer jv = new JasperViewer(jp);
               jv.setVisible(true);
               setTitle("Reporte");
           } catch (JRException ex) {
               Logger.getLogger(Equipo.class.getName()).log(Level.SEVERE, null, ex);
           }     
    }//GEN-LAST:event_desActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acti;
    private javax.swing.JComboBox combostatus;
    private javax.swing.JButton des;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_evento2;
    // End of variables declaration//GEN-END:variables
}
