/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminGral;

import Conexion.Conexion;
import Joption.Joption;
import Joption.Joptionx;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JaviieR
 */
public class RegistroAdminGral extends javax.swing.JFrame {
    DefaultTableModel model;
    Connection conn;
    Statement sent;
   Joption icon = new Joption();
   Joptionx save = new Joptionx(); 
   
 

    /**
     * Creates new form RegistroAdminGral
     */
    public RegistroAdminGral() {
        initComponents();
    
        bloquear();
        fech.setText(fechaActual());
         setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Registro Administrador General");
        setIconImage(new ImageIcon(getClass().getResource("admin.png")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("wall.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());
    }
     public static String fechaActual(){
        Date fecha=new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY");
        return formatoFecha.format(fecha);}
     void bloquear(){
        nombre.setEnabled(false);
        apellido.setEnabled(false);
        fich.setEnabled(false);
        emple.setEnabled(false);
        comboedificio.setEnabled(false);
        combotipo.setEnabled(false);
        contra.setEnabled(false);
        recontra.setEnabled(false);
        guardar.setEnabled(false);
        cancelar.setEnabled(false);
        tabla.setEnabled(false);
        nuevo.setEnabled(true);
    }
      void desbloquear(){
        nombre.setEnabled(true);
        apellido.setEnabled(true);
        fich.setEnabled(true);
        emple.setEnabled(true);
        comboedificio.setEnabled(true);
        combotipo.setEnabled(true);
        contra.setEnabled(true);
        recontra.setEnabled(true);
        guardar.setEnabled(true);
        cancelar.setEnabled(true);
        nuevo.setEnabled(false);
    }
      void limpiar(){
          nombre.setText("");
        apellido.setText("");
        fich.setText("");
        emple.setSelectedIndex(0);
        comboedificio.setSelectedIndex(0);
        combotipo.setSelectedIndex(0);
        contra.setText("");
        recontra.setText("");
      }
      void cargar(){           
     String [] titulos ={"Nombre","Apellido","Tipo","No.Ficha","Dia de Registro","Edificio Laboral","Tipo de sesion","Contraseña"};
 String sql = "SELECT * FROM administrador ";

 model= new DefaultTableModel(null,titulos);
 Conexion cc= new Conexion();
 Connection cn = cc.getConnection();

        try {
          Statement   st = cn.createStatement();
          ResultSet rs=st.executeQuery(sql);
          
          String [] fila = new String[15];

  if(rs.next()){
    
            fila[0] = rs.getString("nom_admi");
            fila[1] = rs.getString("ape_admi");
            fila[2] = rs.getString("tipo_invi");
            fila[3] = rs.getString("no_ficha");
            fila[4] = rs.getString("fecha"); 
            fila[5] = rs.getString("edificio");
            fila[6] = rs.getString("tipo_sesion");
            fila[7] = rs.getString("contra_usu");
            
      model.addRow(fila);

  }

        tabla.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(RegistroAdminGral.class.getName()).log(Level.SEVERE, null, ex);
        }

      }       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        contra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboedificio = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        emple = new javax.swing.JComboBox();
        fich = new javax.swing.JTextField();
        combotipo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        fech = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        recontra = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        nuevo = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tipo de Sesion* : ");

        contra.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        contra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        contra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre(s)* : ");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        comboedificio.setBackground(new java.awt.Color(0, 102, 255));
        comboedificio.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        comboedificio.setForeground(new java.awt.Color(255, 255, 255));
        comboedificio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Area de soporte", "Recursos Humanos", "Usuario Nuevo o practicante" }));
        comboedificio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        comboedificio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboedificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboedificioActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contraseña* :");

        emple.setBackground(new java.awt.Color(0, 102, 255));
        emple.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        emple.setForeground(new java.awt.Color(255, 255, 255));
        emple.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Empleado" }));
        emple.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        emple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        emple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleActionPerformed(evt);
            }
        });

        fich.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        fich.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fich.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fich.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fichActionPerformed(evt);
            }
        });
        fich.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fichKeyTyped(evt);
            }
        });

        combotipo.setBackground(new java.awt.Color(0, 102, 255));
        combotipo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        combotipo.setForeground(new java.awt.Color(255, 255, 255));
        combotipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMINISTRADOR", "INVITADO" }));
        combotipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        combotipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combotipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotipoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Edificio Laboral :");

        fech.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        fech.setForeground(new java.awt.Color(255, 255, 255));
        fech.setText("DD/MM/YYYY");

        apellido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        apellido.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Repita* : ");

        recontra.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        recontra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        recontra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        recontra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        recontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recontraActionPerformed(evt);
            }
        });

        nombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido(s)* :");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No. Ficha* :");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Tipo", "No.Ficha", "Dia de  Registro", "Ubicacion", "Tipo de Accesso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(tabla);

        nuevo.setBackground(new java.awt.Color(0, 0, 0));
        nuevo.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        nuevo.setForeground(new java.awt.Color(255, 255, 255));
        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminGral/testimonials-ti-ico.png"))); // NOI18N
        nuevo.setText("NUEVO");
        nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        guardar.setBackground(new java.awt.Color(0, 0, 0));
        guardar.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminGral/boton-guardar.gif"))); // NOI18N
        guardar.setText("GUARDAR");
        guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(0, 0, 0));
        cancelar.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminGral/cancelar.png"))); // NOI18N
        cancelar.setText("CANCELAR");
        cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminGral/salir.png"))); // NOI18N
        jButton4.setText("SALIR");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nombre)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(emple, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fich, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(apellido))
                            .addComponent(fech))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recontra)
                            .addComponent(comboedificio, 0, 181, Short.MAX_VALUE)
                            .addComponent(combotipo, 0, 1, Short.MAX_VALUE)
                            .addComponent(contra, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(comboedificio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emple, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fech, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(recontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
        nombre.transferFocus();
    }//GEN-LAST:event_nombreActionPerformed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreKeyTyped

    private void apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoActionPerformed
        // TODO add your handling code here:
        apellido.transferFocus();
    }//GEN-LAST:event_apellidoActionPerformed

    private void fichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fichActionPerformed
        // TODO add your handling code here
        fich.transferFocus();
    }//GEN-LAST:event_fichActionPerformed

    private void fichKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fichKeyTyped
        // TODO add your handling code here:
        char C = evt.getKeyChar();
        if(C<'0' || C>'9') evt.consume();
        if(fich.getText().length()>=6){
            evt.consume();
        }
    }//GEN-LAST:event_fichKeyTyped

    private void empleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleActionPerformed

    private void comboedificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboedificioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboedificioActionPerformed

    private void combotipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotipoActionPerformed
        // TODO add your handling code here:
        combotipo.transferFocus();
    }//GEN-LAST:event_combotipoActionPerformed

    private void contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraActionPerformed
        // TODO add your handling code here:
        contra.transferFocus();
    }//GEN-LAST:event_contraActionPerformed

    private void recontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recontraActionPerformed
        // TODO add your handling code here:
        recontra.transferFocus();
    }//GEN-LAST:event_recontraActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        Conexion cc = new Conexion();
        Connection cn = cc.getConnection();
     
        
        String nom_admi,ape_admi,tipo_invi,no_ficha,fecha,edificio,tipo_sesion,contra_usu;
        String sql="";
        nom_admi=nombre.getText();
        contra_usu=contra.getText();
        ape_admi=apellido.getText();
        fecha=fech.getText();
        no_ficha=fich.getText();
        tipo_sesion=combotipo.getSelectedItem().toString();
        edificio=comboedificio.getSelectedItem().toString();
        tipo_invi=emple.getSelectedItem().toString();
        //campos obligatorios
        if(combotipo.getSelectedItem().toString().equals("")){
         JOptionPane.showMessageDialog(null,"Los Campos Marcados (*) Son Necesarios!","ERROR",JOptionPane.ERROR_MESSAGE,save);   
        }
        if(nombre.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Los Campos Marcados (*) Son Necesarios!","ERROR",JOptionPane.ERROR_MESSAGE,save);
             return;        
              }
        if(fich.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Los Campos Marcados (*) Son Necesarios!","ERROR",JOptionPane.ERROR_MESSAGE,save);
             return;        
              }    
        if(contra.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Los Campos Marcados (*) Son Necesarios!","ERROR",JOptionPane.ERROR_MESSAGE,save);
             return;        
              }
        if(recontra.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Los Campos Marcados (*) Son Necesarios!","ERROR",JOptionPane.ERROR_MESSAGE,save);
             return;        
              }
        //sentencia SQL
        sql="INSERT INTO administrador(nom_admi,ape_admi,tipo_invi,no_ficha,fecha,edificio,tipo_sesion,contra_usu) VALUES (?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement psd =cn.prepareStatement(sql);
            psd.setString(1, nom_admi);
            psd.setString(2, ape_admi);
            psd.setString(3, tipo_invi);
            psd.setString(4,no_ficha);
            psd.setString(5,fecha);
            psd.setString(6,edificio);
            psd.setString(7, tipo_sesion);
            psd.setString(8, contra_usu);
           
           if(contra.getText() == null ? recontra.getText() == null : contra.getText().equals(recontra.getText())){      
           int n=psd.executeUpdate();
           if (n>0){
             cargar();
             JOptionPane.showMessageDialog(null,"Administrador Autorizado!","REGISTRADO",JOptionPane.PLAIN_MESSAGE,icon);
              
               limpiar();
               bloquear();
            }
           
           }else{
     JOptionPane.showMessageDialog(null,"Las contraseñas no coinciden, VERIFIQUE!","ERROR",JOptionPane.ERROR_MESSAGE,save);
               } 
        } catch (SQLException ex) {
            Logger.getLogger(RegistroAdminGral.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        bloquear();
    }//GEN-LAST:event_cancelarActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
        desbloquear();
    }//GEN-LAST:event_nuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAdminGral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAdminGral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAdminGral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAdminGral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAdminGral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox comboedificio;
    private javax.swing.JComboBox combotipo;
    private javax.swing.JTextField contra;
    private javax.swing.JComboBox emple;
    private javax.swing.JLabel fech;
    private javax.swing.JTextField fich;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton nuevo;
    private javax.swing.JTextField recontra;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
