/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Actualizar;

import Conexion.Conexion;
import Joption.Joption;
import Joption.Joptionx;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author JaviieR
 */
public class DatosEditarB extends javax.swing.JFrame {
      Joption icon = new Joption();
    Joptionx save = new Joptionx(); 

    /**
     * Creates new form DatosEditarB
     */
    public DatosEditarB() {
        initComponents();
          setTitle("Datos Usuarios");
        setResizable(false);
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("actualizar.png")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("wall.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        equipo = new javax.swing.JComboBox();
        resolucion = new javax.swing.JLabel();
        cajaresolucion = new javax.swing.JTextField();
        ip = new javax.swing.JLabel();
        cajaip = new javax.swing.JTextField();
        hdmi = new javax.swing.JLabel();
        combohdmi = new javax.swing.JComboBox();
        combousb = new javax.swing.JComboBox();
        usb = new javax.swing.JLabel();
        cajaimpresora = new javax.swing.JTextField();
        impresora = new javax.swing.JLabel();
        cajaram = new javax.swing.JTextField();
        ram = new javax.swing.JLabel();
        dd = new javax.swing.JLabel();
        cajadd = new javax.swing.JTextField();
        impresora1 = new javax.swing.JLabel();
        cajamarca = new javax.swing.JTextField();
        cajamodelo = new javax.swing.JTextField();
        impresora2 = new javax.swing.JLabel();
        cajapulgadas = new javax.swing.JTextField();
        pulgadas = new javax.swing.JLabel();
        lector = new javax.swing.JLabel();
        combolector = new javax.swing.JComboBox();
        impresora3 = new javax.swing.JLabel();
        cajaserie = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        combocompañia = new javax.swing.JComboBox();
        compañia = new javax.swing.JLabel();
        cajapertenece = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ubicacion = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        activo = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        sala = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cajainmo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observa = new javax.swing.JTextArea();
        usuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Caracteristicas del Equipo ", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Sitka Text", 2, 14), java.awt.Color.white)); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("*Tipo de Equipo:");

        equipo.setBackground(new java.awt.Color(0, 102, 255));
        equipo.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        equipo.setForeground(new java.awt.Color(255, 255, 255));
        equipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Seleccione--", "Impresora", "PC", "Laptop", "EQ.Video Conferencia", "Scanner", "Proyector" }));
        equipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        equipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipoActionPerformed(evt);
            }
        });

        resolucion.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        resolucion.setForeground(new java.awt.Color(0, 51, 102));
        resolucion.setText("Resolucion :");

        cajaresolucion.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajaresolucion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaresolucion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaresolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaresolucionActionPerformed(evt);
            }
        });

        ip.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        ip.setForeground(new java.awt.Color(0, 51, 102));
        ip.setText("Direccion ip :");

        cajaip.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajaip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaip.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaipActionPerformed(evt);
            }
        });

        hdmi.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        hdmi.setForeground(new java.awt.Color(0, 51, 102));
        hdmi.setText("Puerto HMDI :");

        combohdmi.setBackground(new java.awt.Color(0, 102, 255));
        combohdmi.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        combohdmi.setForeground(new java.awt.Color(255, 255, 255));
        combohdmi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "SI", "NO" }));
        combohdmi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        combohdmi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combohdmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combohdmiActionPerformed(evt);
            }
        });

        combousb.setBackground(new java.awt.Color(0, 102, 255));
        combousb.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        combousb.setForeground(new java.awt.Color(255, 255, 255));
        combousb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "SI", "NO" }));
        combousb.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        combousb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combousb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combousbActionPerformed(evt);
            }
        });

        usb.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        usb.setForeground(new java.awt.Color(0, 51, 102));
        usb.setText("Puertos USB :");

        cajaimpresora.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajaimpresora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaimpresora.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaimpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaimpresoraActionPerformed(evt);
            }
        });

        impresora.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        impresora.setForeground(new java.awt.Color(0, 51, 102));
        impresora.setText("Tipo de Impresora:");

        cajaram.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajaram.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaram.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaramActionPerformed(evt);
            }
        });

        ram.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        ram.setForeground(new java.awt.Color(0, 51, 102));
        ram.setText("Tamaño de RAM : ");

        dd.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        dd.setForeground(new java.awt.Color(0, 51, 102));
        dd.setText("Tamaño de Disco Duro :");

        cajadd.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajadd.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaddActionPerformed(evt);
            }
        });

        impresora1.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        impresora1.setForeground(new java.awt.Color(0, 51, 102));
        impresora1.setText("Marcar :");

        cajamarca.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajamarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajamarca.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajamarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajamarcaActionPerformed(evt);
            }
        });

        cajamodelo.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajamodelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajamodelo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajamodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajamodeloActionPerformed(evt);
            }
        });

        impresora2.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        impresora2.setForeground(new java.awt.Color(0, 51, 102));
        impresora2.setText("Modelo:");

        cajapulgadas.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajapulgadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajapulgadas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajapulgadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajapulgadasActionPerformed(evt);
            }
        });

        pulgadas.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        pulgadas.setForeground(new java.awt.Color(0, 51, 102));
        pulgadas.setText("Pulgadas : ");

        lector.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        lector.setForeground(new java.awt.Color(0, 51, 102));
        lector.setText("Cuenta Con Lector DVD :");

        combolector.setBackground(new java.awt.Color(0, 102, 255));
        combolector.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        combolector.setForeground(new java.awt.Color(255, 255, 255));
        combolector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "SI", "NO" }));
        combolector.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        combolector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combolector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combolectorActionPerformed(evt);
            }
        });

        impresora3.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        impresora3.setForeground(new java.awt.Color(0, 51, 102));
        impresora3.setText("No.Serie :");

        cajaserie.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajaserie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaserie.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaserie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaserieActionPerformed(evt);
            }
        });

        txtid.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ram)
                                .addComponent(resolucion)
                                .addComponent(pulgadas)
                                .addComponent(lector)
                                .addComponent(dd, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(hdmi)
                            .addComponent(usb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cajapulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cajadd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cajaram, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cajaresolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(combohdmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(impresora2)
                                        .addComponent(impresora1)
                                        .addComponent(impresora)
                                        .addComponent(ip)
                                        .addComponent(impresora3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cajaimpresora, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cajamarca, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cajaip, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cajamodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(combolector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cajaserie, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(combousb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 169, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ip, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(impresora)
                        .addGap(13, 13, 13)
                        .addComponent(impresora1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaresolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ram, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajapulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(impresora2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lector, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combolector, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cajaip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(cajaimpresora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cajamarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cajamodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(impresora3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hdmi)
                    .addComponent(combohdmi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usb)
                    .addComponent(combousb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Caracteristicas", jPanel2);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Datos de Empresa", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Sitka Text", 2, 14), java.awt.Color.white)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Pertenece: ");

        combocompañia.setBackground(new java.awt.Color(0, 102, 255));
        combocompañia.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        combocompañia.setForeground(new java.awt.Color(255, 255, 255));
        combocompañia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Propiedad", "PEMEX", "COMPAÑIA" }));
        combocompañia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        combocompañia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combocompañia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocompañiaActionPerformed(evt);
            }
        });

        compañia.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        compañia.setForeground(new java.awt.Color(0, 51, 102));
        compañia.setText("Compañia:");

        cajapertenece.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cajapertenece.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajapertenece.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajapertenece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaperteneceActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("Se registra en:");

        ubicacion.setBackground(new java.awt.Color(0, 102, 255));
        ubicacion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ubicacion.setForeground(new java.awt.Color(255, 255, 255));
        ubicacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ubicacion de Equipo", "Edif. KAAN CEIBA", "Edif.Inspeccion Tubular", "Edif. U OSSO" }));
        ubicacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ubicacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ubicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubicacionActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("Estado:");

        activo.setBackground(new java.awt.Color(0, 102, 255));
        activo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        activo.setForeground(new java.awt.Color(255, 255, 255));
        activo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Status", "ACTIVO", "DESHABILITADO" }));
        activo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        activo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        activo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activoActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 102));
        jLabel18.setText("Nombre de sala:");

        sala.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        sala.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sala.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        sala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 102));
        jLabel19.setText("Inmovilizado :");

        cajainmo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cajainmo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajainmo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajainmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajainmoActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Observaciones", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Sitka Text", 2, 14))); // NOI18N

        observa.setColumns(20);
        observa.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        observa.setForeground(new java.awt.Color(0, 51, 102));
        observa.setRows(5);
        observa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        observa.setSelectionColor(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(observa);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        usuario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Usuario :");

        fecha.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fecha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("Fecha :");

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Actualizar/actualizar.png"))); // NOI18N
        jButton3.setText("ACTUALIZAR");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Actualizar/salir.png"))); // NOI18N
        jButton4.setText("SALIR");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(compañia)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sala)
                                    .addComponent(cajapertenece)
                                    .addComponent(cajainmo)
                                    .addComponent(activo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combocompañia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(101, 101, 101)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(usuario)
                                        .addGap(15, 15, 15))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jButton3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combocompañia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compañia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajapertenece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(activo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajainmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Datos Generales", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipoActionPerformed
        // TODO add your handling code here:
        int bloqueo = equipo.getSelectedIndex();
        if(bloqueo == 1){

            impresora.setVisible(true);
            cajaimpresora.setVisible(true);
            ip.setVisible(false);
            cajaip.setVisible(false);
            resolucion.setVisible(false);
            cajaresolucion.setVisible(false);
            ram.setVisible(false);
            cajaram.setVisible(false);
            dd.setVisible(false);
            cajadd.setVisible(false);
            pulgadas.setVisible(false);
            cajapulgadas.setVisible(false);
            lector.setVisible(false);
            combolector.setVisible(false);
            hdmi.setVisible(false);
            combohdmi.setVisible(false);
            usb.setVisible(false);
            combousb.setVisible(false);
        }
        if(bloqueo == 2){

            resolucion.setVisible(true);
            cajaresolucion.setVisible(true);
            ram.setVisible(true);
            cajaram.setVisible(true);
            dd.setVisible(true);
            cajadd.setVisible(true);
            pulgadas.setVisible(true);
            cajapulgadas.setVisible(true);
            lector.setVisible(true);
            combolector.setVisible(true);
            hdmi.setVisible(true);
            combohdmi.setVisible(true);
            usb.setVisible(true);
            combousb.setVisible(true);
            ip.setVisible(false);
            cajaip.setVisible(false);
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);

        }
        if(bloqueo == 3){

            resolucion.setVisible(true);
            cajaresolucion.setVisible(true);
            ram.setVisible(true);
            cajaram.setVisible(true);
            dd.setVisible(true);
            cajadd.setVisible(true);
            pulgadas.setVisible(true);
            cajapulgadas.setVisible(true);
            lector.setVisible(true);
            combolector.setVisible(true);
            hdmi.setVisible(true);
            combohdmi.setVisible(true);
            usb.setVisible(true);
            combousb.setVisible(true);
            ip.setVisible(false);
            cajaip.setVisible(false);
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);
        }
        if(bloqueo==4){
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);
            ip.setVisible(true);
            cajaip.setVisible(true);
            resolucion.setVisible(false);
            cajaresolucion.setVisible(false);
            ram.setVisible(false);
            cajaram.setVisible(false);
            dd.setVisible(false);
            cajadd.setVisible(false);
            pulgadas.setVisible(false);
            cajapulgadas.setVisible(false);
            lector.setVisible(false);
            combolector.setVisible(false);
            hdmi.setVisible(false);
            combohdmi.setVisible(false);
            usb.setVisible(false);
            combousb.setVisible(false);

        }
        if(bloqueo == 5){

            resolucion.setVisible(true);
            cajaresolucion.setVisible(true);
            hdmi.setVisible(true);
            combohdmi.setVisible(true);
            usb.setVisible(true);
            combousb.setVisible(true);
            ram.setVisible(false);
            cajaram.setVisible(false);
            dd.setVisible(false);
            cajadd.setVisible(false);
            pulgadas.setVisible(false);
            cajapulgadas.setVisible(false);
            lector.setVisible(false);
            combolector.setVisible(false);
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);
            ip.setVisible(false);
            cajaip.setVisible(false);

        }
        if(bloqueo == 6){
            resolucion.setVisible(true);
            cajaresolucion.setVisible(true);
            hdmi.setVisible(true);
            combohdmi.setVisible(true);
            usb.setVisible(true);
            combousb.setVisible(true);
            ram.setVisible(false);
            cajaram.setVisible(false);
            dd.setVisible(false);
            cajadd.setVisible(false);
            pulgadas.setVisible(false);
            cajapulgadas.setVisible(false);
            lector.setVisible(false);
            combolector.setVisible(false);
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);
            ip.setVisible(false);
            cajaip.setVisible(false);

        }

    }//GEN-LAST:event_equipoActionPerformed

    private void cajaresolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaresolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaresolucionActionPerformed

    private void cajaipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaipActionPerformed

    private void combohdmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combohdmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combohdmiActionPerformed

    private void combousbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combousbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combousbActionPerformed

    private void cajaimpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaimpresoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaimpresoraActionPerformed

    private void cajaramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaramActionPerformed

    private void cajaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaddActionPerformed

    private void cajamarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajamarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajamarcaActionPerformed

    private void cajamodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajamodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajamodeloActionPerformed

    private void cajapulgadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajapulgadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajapulgadasActionPerformed

    private void combolectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combolectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combolectorActionPerformed

    private void cajaserieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaserieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaserieActionPerformed

    private void combocompañiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocompañiaActionPerformed
        // TODO add your handling code here:
        int bloqueo = combocompañia.getSelectedIndex();
        if(bloqueo==2){
            compañia.setVisible(true);
            cajapertenece.setVisible(true);
            cajapertenece.setEnabled(true);
            cajapertenece.setText("");
        }
        if(bloqueo==1){
            cajapertenece.setText("PEMEX");
            cajapertenece.setVisible(false);
            compañia.setVisible(false);

        }else {

        }
    }//GEN-LAST:event_combocompañiaActionPerformed

    private void cajaperteneceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaperteneceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaperteneceActionPerformed

    private void ubicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubicacionActionPerformed

    private void activoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activoActionPerformed

    private void salaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaActionPerformed
        // TODO add your handling code here:
        sala.transferFocus();
    }//GEN-LAST:event_salaActionPerformed

    private void cajainmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajainmoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajainmoActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Conexion cc= new Conexion();
        Connection cn = cc.getConnection();
        PreparedStatement pps;
        try {
            pps = cn.prepareStatement("UPDATE articulos SET nom_cli='"+usuario.getText()
                +"',equip='"+equipo.getSelectedItem().toString()+"',marc='"+cajamarca.getText()+"',model='"+cajamodelo.getText()+"',seri='"+cajaserie.getText()+
                "' ,inmo='"+cajainmo.getText()+"',ubi='"+ubicacion.getSelectedItem().toString()+"',acti='"+activo.getSelectedItem().toString()+
                "',nom_sala='"+sala.getText()+"',pertenece='"+combocompañia.getSelectedItem().toString()+
                "',nom_pertenece='"+cajapertenece.getText()+"',obser='"+observa.getText()+"',fecha='"+fecha.getText()+"',resolucion ='"+cajaresolucion.getText()+"',ram='"+cajaram.getText()+"',dd='"+cajadd.getText()+"',pulgadas='"+cajapulgadas.getText()+"',lector='"+combolector.getSelectedItem().toString()+"',ip='"+cajaip.getText()+"',impresora='"+cajaimpresora.getText()+"',hdmi='"+combohdmi.getSelectedItem().toString()+"',usb='"+combousb.getSelectedItem().toString()+"' WHERE seri ='"+txtid.getText()+"'");
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Datos Actualizados!","CORRECTO",JOptionPane.PLAIN_MESSAGE,icon);
        this.dispose();
       
        } catch (SQLException ex) {
            Logger.getLogger(DatosEditarB.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosEditarB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosEditarB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosEditarB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosEditarB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosEditarB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox activo;
    public static javax.swing.JTextField cajadd;
    public static javax.swing.JTextField cajaimpresora;
    public static javax.swing.JTextField cajainmo;
    public static javax.swing.JTextField cajaip;
    public static javax.swing.JTextField cajamarca;
    public static javax.swing.JTextField cajamodelo;
    public static javax.swing.JTextField cajapertenece;
    public static javax.swing.JTextField cajapulgadas;
    public static javax.swing.JTextField cajaram;
    public static javax.swing.JTextField cajaresolucion;
    public static javax.swing.JTextField cajaserie;
    public static javax.swing.JComboBox combocompañia;
    public static javax.swing.JComboBox combohdmi;
    public static javax.swing.JComboBox combolector;
    public static javax.swing.JComboBox combousb;
    private javax.swing.JLabel compañia;
    private javax.swing.JLabel dd;
    public static javax.swing.JComboBox equipo;
    public static javax.swing.JTextField fecha;
    private javax.swing.JLabel hdmi;
    private javax.swing.JLabel impresora;
    private javax.swing.JLabel impresora1;
    private javax.swing.JLabel impresora2;
    private javax.swing.JLabel impresora3;
    private javax.swing.JLabel ip;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lector;
    public static javax.swing.JTextArea observa;
    private javax.swing.JLabel pulgadas;
    private javax.swing.JLabel ram;
    private javax.swing.JLabel resolucion;
    public static javax.swing.JTextField sala;
    public static javax.swing.JTextField txtid;
    public static javax.swing.JComboBox ubicacion;
    private javax.swing.JLabel usb;
    public static javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
